version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qna_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  flask-app:
    build: .
    environment:
      - OPENAI_API_KEY=sk-UYeD9ZboNBPpPxbSA6UmmN1FbbxRXS-r5kv4JARUyfT3BlbkFJ46S5hPyYjAhjlv06SYqREsjau4dkvgpy4wxDopj6MA
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata:
